### ISSUE TITLE
Add support for viewing multiple wikis

### ISSUE THREAD

**Issue by Tellios** [Tellios/staticless#2]
# Description
To make it even easier to host wikis it should be possible to opt-in the ability to switch between multiple wikis from the Staticless frontend.

To be able to support this, the configuration has to change to allow for multiple projects to be configured. The frontend has to be adapted to support the switch between wikis, and the data passed between the backend and frontend has to contain some kind of id that associates the wiki pages with the correct project.

# Tasks
- [x] Investigate the best alternative to identify wikis on (generated id? id from gitlab? user configured id?)
- [x] Update routes to include id
- [x] Update backend endpoints and caching to support id
- [x] Add frontend support for new endpoints
- [x] Add ability to switch wiki in frontend
- [x] Clean-up code

**Comment by Tellios** [comment]
#11 Closes this issue
